name: 'workflows日志自动清理'

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@main

    - name: Set git
      run : |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        sudo timedatectl set-timezone "Asia/Shanghai"
        
    - name: Delete workflow runs
      uses: Jejz168/delete-workflow-runs@main
      with:
          retain_days: 3
          keep_minimum_runs: 0
