name: '52Pojie Auto Sign'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18,10 * * *'

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        
      - name: Initialize Python
        uses: actions/setup-python@main
        with:
          python-version: '3.8'
          
      - name: install
        run: |
          python -m pip install --upgrade requests
          pip install beautifulsoup4
          
      - name: Checkin
        env:
          POJIE: ${{ secrets.POJIE }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
        run: python3 main.py
