name: '52Pojie Auto Sign'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 18,10 * * *'

jobs:
  sign:
    runs-on: ubuntu-latest
    steps:
      - name: '代码检查'
        uses: actions/checkout@main
      - name: '初始化Python'
        uses: actions/setup-python@master
        with:
          python-version: '3.7'
      - name: '安装依赖包'
        run: |
          python -m pip install --upgrade requests
          pip install beautifulsoup4
      - name: '开始签到'
        env:
          POJIE: ${{ secrets.POJIE }}
          PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN }}
        run: python main.py
